# Generated by Django 4.2.14 on 2024-07-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('short_description', models.TextField(max_length=255)),
                ('descricao', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='product_images/%Y/%m')),
                ('slug', models.SlugField(unique=True)),
                ('price_mkt', models.FloatField(default=0)),
                ('price_mkt_promo', models.FloatField(default=0)),
                ('product_type', models.CharField(choices=[('V', 'Variation'), ('S', 'Simple')], default='V', max_length=1)),
            ],
        ),
    ]
